// This is a list of icon codes for the entypo.ttf font

#if !defined(__CATGL_ENTYPO_H)
#define __CATGL_ENTYPO_H

#define CATGL_ICON_PHONE                0x1F4DE
#define CATGL_ICON_MOBILE               0x1F4F1
#define CATGL_ICON_MOUSE                0xE789
#define CATGL_ICON_ADDRESS              0xE723
#define CATGL_ICON_MAIL                 0x2709
#define CATGL_ICON_PAPER_PLANE          0x1F53F
#define CATGL_ICON_PENCIL               0x270E
#define CATGL_ICON_FEATHER              0x2712
#define CATGL_ICON_ATTACH               0x1F4CE
#define CATGL_ICON_INBOX                0xE777
#define CATGL_ICON_REPLY                0xE712
#define CATGL_ICON_REPLY_ALL            0xE713
#define CATGL_ICON_FORWARD              0x27A6
#define CATGL_ICON_USER                 0x1F464
#define CATGL_ICON_USERS                0x1F465
#define CATGL_ICON_ADD_USER             0xE700
#define CATGL_ICON_VCARD                0xE722
#define CATGL_ICON_EXPORT               0xE715
#define CATGL_ICON_LOCATION             0xE724
#define CATGL_ICON_MAP                  0xE727
#define CATGL_ICON_COMPASS              0xE728
#define CATGL_ICON_DIRECTION            0x27A2
#define CATGL_ICON_HAIR_CROSS           0x1F3AF
#define CATGL_ICON_SHARE                0xE73C
#define CATGL_ICON_SHAREABLE            0xE73E
#define CATGL_ICON_HEART                0x2665
#define CATGL_ICON_HEART_EMPTY          0x2661
#define CATGL_ICON_STAR                 0x2605
#define CATGL_ICON_STAR_EMPTY           0x2606
#define CATGL_ICON_THUMBS_UP            0x1F44D
#define CATGL_ICON_THUMBS_DOWN          0x1F44E
#define CATGL_ICON_CHAT                 0xE720
#define CATGL_ICON_COMMENT              0xE718
#define CATGL_ICON_QUOTE                0x275E
#define CATGL_ICON_HOME                 0x2302
#define CATGL_ICON_POPUP                0xE74C
#define CATGL_ICON_SEARCH               0x1F50D
#define CATGL_ICON_FLASHLIGHT           0x1F526
#define CATGL_ICON_PRINT                0xE716
#define CATGL_ICON_BELL                 0x1F514
#define CATGL_ICON_LINK                 0x1F517
#define CATGL_ICON_FLAG                 0x2691
#define CATGL_ICON_COG                  0x2699
#define CATGL_ICON_TOOLS                0x2692
#define CATGL_ICON_TROPHY               0x1F3C6
#define CATGL_ICON_TAG                  0xE70C
#define CATGL_ICON_CAMERA               0x1F4F7
#define CATGL_ICON_MEGAPHONE            0x1F4E3
#define CATGL_ICON_MOON                 0x263D
#define CATGL_ICON_PALETTE              0x1F3A8
#define CATGL_ICON_LEAF                 0x1F342
#define CATGL_ICON_NOTE                 0x266A
#define CATGL_ICON_BEAMED_NOTE          0x266B
#define CATGL_ICON_NEW                  0x1F4A5
#define CATGL_ICON_GRADUATION_CAP       0x1F393
#define CATGL_ICON_BOOK                 0x1F4D5
#define CATGL_ICON_NEWSPAPER            0x1F4F0
#define CATGL_ICON_BAG                  0x1F45C
#define CATGL_ICON_AIRPLANE             0x2708
#define CATGL_ICON_LIFEBUOY             0xE788
#define CATGL_ICON_EYE                  0xE70A
#define CATGL_ICON_CLOCK                0x1F554
#define CATGL_ICON_MIC                  0x1F3A4
#define CATGL_ICON_CALENDAR             0x1F4C5
#define CATGL_ICON_FLASH                0x26A1
#define CATGL_ICON_THUNDER_CLOUD        0x26C8
#define CATGL_ICON_DROPLET              0x1F4A7
#define CATGL_ICON_CD                   0x1F4BF
#define CATGL_ICON_BRIEFCASE            0x1F4BC
#define CATGL_ICON_AIR                  0x1F4A8
#define CATGL_ICON_HOURGLASS            0x23F3
#define CATGL_ICON_GAUGE                0x1F6C7
#define CATGL_ICON_LANGUAGE             0x1F394
#define CATGL_ICON_NETWORK              0xE776
#define CATGL_ICON_KEY                  0x1F511
#define CATGL_ICON_BATTERY              0x1F50B
#define CATGL_ICON_BUCKET               0x1F4FE
#define CATGL_ICON_MAGNET               0xE7A1
#define CATGL_ICON_DRIVE                0x1F4FD
#define CATGL_ICON_CUP                  0x2615
#define CATGL_ICON_ROCKET               0x1F680
#define CATGL_ICON_BRUSH                0xE79A
#define CATGL_ICON_SUITCASE             0x1F6C6
#define CATGL_ICON_TRAFFIC_CONE         0x1F6C8
#define CATGL_ICON_GLOBE                0x1F30E
#define CATGL_ICON_KEYBOARD             0x2328
#define CATGL_ICON_BROWSER              0xE74E
#define CATGL_ICON_PUBLISH              0xE74D
#define CATGL_ICON_PROGRESS_3           0xE76B
#define CATGL_ICON_PROGRESS_2           0xE76A
#define CATGL_ICON_PROGRESS_1           0xE769
#define CATGL_ICON_PROGRESS_0           0xE768
#define CATGL_ICON_LIGHT_DOWN           0x1F505
#define CATGL_ICON_LIGHT_UP             0x1F506
#define CATGL_ICON_ADJUST               0x25D1
#define CATGL_ICON_CODE                 0xE714
#define CATGL_ICON_MONITOR              0x1F4BB
#define CATGL_ICON_INFINITY             0x221E
#define CATGL_ICON_LIGHT_BULB           0x1F4A1
#define CATGL_ICON_CREDIT_CARD          0x1F4B3
#define CATGL_ICON_DATABASE             0x1F4F8
#define CATGL_ICON_VOICEMAIL            0x2707
#define CATGL_ICON_CLIPBOARD            0x1F4CB
#define CATGL_ICON_CART                 0xE73D
#define CATGL_ICON_BOX                  0x1F4E6
#define CATGL_ICON_TICKET               0x1F3AB
#define CATGL_ICON_RSS                  0xE73A
#define CATGL_ICON_SIGNAL               0x1F4F6
#define CATGL_ICON_THERMOMETER          0x1F4FF
#define CATGL_ICON_WATER                0x1F4A6
#define CATGL_ICON_SWEDEN               0xF601
#define CATGL_ICON_LINE_GRAPH           0x1F4C8
#define CATGL_ICON_PIE_CHART            0x25F4
#define CATGL_ICON_BAR_GRAPH            0x1F4CA
#define CATGL_ICON_AREA_GRAPH           0x1F53E
#define CATGL_ICON_LOCK                 0x1F512
#define CATGL_ICON_LOCK_OPEN            0x1F513
#define CATGL_ICON_LOGOUT               0xE741
#define CATGL_ICON_LOGIN                0xE740
#define CATGL_ICON_CHECK                0x2713
#define CATGL_ICON_CROSS                0x274C
#define CATGL_ICON_SQUARED_MINUS        0x229F
#define CATGL_ICON_SQUARED_PLUS         0x229E
#define CATGL_ICON_SQUARED_CROSS        0x274E
#define CATGL_ICON_CIRCLED_MINUS        0x2296
#define CATGL_ICON_CIRCLED_PLUS         0x2295
#define CATGL_ICON_CIRCLED_CROSS        0x2716
#define CATGL_ICON_MINUS                0x2796
#define CATGL_ICON_PLUS                 0x2795
#define CATGL_ICON_ERASE                0x232B
#define CATGL_ICON_BLOCK                0x1F6AB
#define CATGL_ICON_INFO                 0x2139
#define CATGL_ICON_CIRCLED_INFO         0xE705
#define CATGL_ICON_HELP                 0x2753
#define CATGL_ICON_CIRCLED_HELP         0xE704
#define CATGL_ICON_WARNING              0x26A0
#define CATGL_ICON_CYCLE                0x1F504
#define CATGL_ICON_CW                   0x27F3
#define CATGL_ICON_CCW                  0x27F2
#define CATGL_ICON_SHUFFLE              0x1F500
#define CATGL_ICON_BACK                 0x1F519
#define CATGL_ICON_LEVEL_DOWN           0x21B3
#define CATGL_ICON_RETWEET              0xE717
#define CATGL_ICON_LOOP                 0x1F501
#define CATGL_ICON_BACK_IN_TIME         0xE771
#define CATGL_ICON_LEVEL_UP             0x21B0
#define CATGL_ICON_SWITCH               0x21C6
#define CATGL_ICON_NUMBERED_LIST        0xE005
#define CATGL_ICON_ADD_TO_LIST          0xE003
#define CATGL_ICON_LAYOUT               0x268F
#define CATGL_ICON_LIST                 0x2630
#define CATGL_ICON_TEXT_DOC             0x1F4C4
#define CATGL_ICON_TEXT_DOC_INVERTED    0xE731
#define CATGL_ICON_DOC                  0xE730
#define CATGL_ICON_DOCS                 0xE736
#define CATGL_ICON_LANDSCAPE_DOC        0xE737
#define CATGL_ICON_PICTURE              0x1F304
#define CATGL_ICON_VIDEO                0x1F3AC
#define CATGL_ICON_MUSIC                0x1F3B5
#define CATGL_ICON_FOLDER               0x1F4C1
#define CATGL_ICON_ARCHIVE              0xE800
#define CATGL_ICON_TRASH                0xE729
#define CATGL_ICON_UPLOAD               0x1F4E4
#define CATGL_ICON_DOWNLOAD             0x1F4E5
#define CATGL_ICON_SAVE                 0x1F4BE
#define CATGL_ICON_INSTALL              0xE778
#define CATGL_ICON_CLOUD                0x2601
#define CATGL_ICON_UPLOAD_CLOUD         0xE711
#define CATGL_ICON_BOOKMARK             0x1F516
#define CATGL_ICON_BOOKMARKS            0x1F4D1
#define CATGL_ICON_OPEN_BOOK            0x1F4D6
#define CATGL_ICON_PLAY                 0x25B6
#define CATGL_ICON_PAUS                 0x2016
#define CATGL_ICON_RECORD               0x25CF
#define CATGL_ICON_STOP                 0x25A0
#define CATGL_ICON_FF                   0x23E9
#define CATGL_ICON_FB                   0x23EA
#define CATGL_ICON_TO_START             0x23EE
#define CATGL_ICON_TO_END               0x23ED
#define CATGL_ICON_RESIZE_FULL          0xE744
#define CATGL_ICON_RESIZE_SMALL         0xE746
#define CATGL_ICON_VOLUME               0x23F7
#define CATGL_ICON_SOUND                0x1F50A
#define CATGL_ICON_MUTE                 0x1F507
#define CATGL_ICON_FLOW_CASCADE         0x1F568
#define CATGL_ICON_FLOW_BRANCH          0x1F569
#define CATGL_ICON_FLOW_TREE            0x1F56A
#define CATGL_ICON_FLOW_LINE            0x1F56B
#define CATGL_ICON_FLOW_PARALLEL        0x1F56C
#define CATGL_ICON_LEFT_BOLD            0xE4AD
#define CATGL_ICON_DOWN_BOLD            0xE4B0
#define CATGL_ICON_UP_BOLD              0xE4AF
#define CATGL_ICON_RIGHT_BOLD           0xE4AE
#define CATGL_ICON_LEFT                 0x2B05
#define CATGL_ICON_DOWN                 0x2B07
#define CATGL_ICON_UP                   0x2B06
#define CATGL_ICON_RIGHT                0x27A1
#define CATGL_ICON_CIRCLED_LEFT         0xE759
#define CATGL_ICON_CIRCLED_DOWN         0xE758
#define CATGL_ICON_CIRCLED_UP           0xE75B
#define CATGL_ICON_CIRCLED_RIGHT        0xE75A
#define CATGL_ICON_TRIANGLE_LEFT        0x25C2
#define CATGL_ICON_TRIANGLE_DOWN        0x25BE
#define CATGL_ICON_TRIANGLE_UP          0x25B4
#define CATGL_ICON_TRIANGLE_RIGHT       0x25B8
#define CATGL_ICON_CHEVRON_LEFT         0xE75D
#define CATGL_ICON_CHEVRON_DOWN         0xE75C
#define CATGL_ICON_CHEVRON_UP           0xE75F
#define CATGL_ICON_CHEVRON_RIGHT        0xE75E
#define CATGL_ICON_CHEVRON_SMALL_LEFT   0xE761
#define CATGL_ICON_CHEVRON_SMALL_DOWN   0xE760
#define CATGL_ICON_CHEVRON_SMALL_UP     0xE763
#define CATGL_ICON_CHEVRON_SMALL_RIGHT  0xE762
#define CATGL_ICON_CHEVRON_THIN_LEFT    0xE765
#define CATGL_ICON_CHEVRON_THIN_DOWN    0xE764
#define CATGL_ICON_CHEVRON_THIN_UP      0xE767
#define CATGL_ICON_CHEVRON_THIN_RIGHT   0xE766
#define CATGL_ICON_LEFT_THIN            0x2190
#define CATGL_ICON_DOWN_THIN            0x2193
#define CATGL_ICON_UP_THIN              0x2191
#define CATGL_ICON_RIGHT_THIN           0x2192
#define CATGL_ICON_ARROW_COMBO          0xE74F
#define CATGL_ICON_THREE_DOTS           0x23F6
#define CATGL_ICON_TWO_DOTS             0x23F5
#define CATGL_ICON_DOT                  0x23F4
#define CATGL_ICON_CC                   0x1F545
#define CATGL_ICON_CC_BY                0x1F546
#define CATGL_ICON_CC_NC                0x1F547
#define CATGL_ICON_CC_NC_EU             0x1F548
#define CATGL_ICON_CC_NC_JP             0x1F549
#define CATGL_ICON_CC_SA                0x1F54A
#define CATGL_ICON_CC_ND                0x1F54B
#define CATGL_ICON_CC_PD                0x1F54C
#define CATGL_ICON_CC_ZERO              0x1F54D
#define CATGL_ICON_CC_SHARE             0x1F54E
#define CATGL_ICON_CC_REMIX             0x1F54F
#define CATGL_ICON_DB_LOGO              0x1F5F9
#define CATGL_ICON_DB_SHAPE             0x1F5FA
#define CATGL_ICON_GITHUB               0xF300
#define CATGL_ICON_C_GITHUB             0xF301
#define CATGL_ICON_FLICKR               0xF303
#define CATGL_ICON_C_FLICKR             0xF304
#define CATGL_ICON_VIMEO                0xF306
#define CATGL_ICON_C_VIMEO              0xF307
#define CATGL_ICON_TWITTER              0xF309
#define CATGL_ICON_C_TWITTER            0xF30A
#define CATGL_ICON_FACEBOOK             0xF30C
#define CATGL_ICON_C_FACEBOOK           0xF30D
#define CATGL_ICON_S_FACEBOOK           0xF30E
#define CATGL_ICON_GOOGLEPLUS           0xF30F
#define CATGL_ICON_C_GOOGLEPLUS         0xF310
#define CATGL_ICON_PINTEREST            0xF312
#define CATGL_ICON_C_PINTEREST          0xF313
#define CATGL_ICON_TUMBLR               0xF315
#define CATGL_ICON_C_TUMBLR             0xF316
#define CATGL_ICON_LINKEDIN             0xF318
#define CATGL_ICON_C_LINKEDIN           0xF319
#define CATGL_ICON_DRIBBBLE             0xF31B
#define CATGL_ICON_C_DRIBBBLE           0xF31C
#define CATGL_ICON_STUMBLEUPON          0xF31E
#define CATGL_ICON_C_STUMBLEUPON        0xF31F
#define CATGL_ICON_LASTFM               0xF321
#define CATGL_ICON_C_LASTFM             0xF322
#define CATGL_ICON_RDIO                 0xF324
#define CATGL_ICON_C_RDIO               0xF325
#define CATGL_ICON_SPOTIFY              0xF327
#define CATGL_ICON_C_SPOTIFY            0xF328
#define CATGL_ICON_QQ                   0xF32A
#define CATGL_ICON_INSTAGRAM            0xF32D
#define CATGL_ICON_DROPBOX              0xF330
#define CATGL_ICON_EVERNOTE             0xF333
#define CATGL_ICON_FLATTR               0xF336
#define CATGL_ICON_SKYPE                0xF339
#define CATGL_ICON_C_SKYPE              0xF33A
#define CATGL_ICON_RENREN               0xF33C
#define CATGL_ICON_SINA_WEIBO           0xF33F
#define CATGL_ICON_PAYPAL               0xF342
#define CATGL_ICON_PICASA               0xF345
#define CATGL_ICON_SOUNDCLOUD           0xF348
#define CATGL_ICON_MIXI                 0xF34B
#define CATGL_ICON_BEHANCE              0xF34E
#define CATGL_ICON_GOOGLE_CIRCLES       0xF351
#define CATGL_ICON_VK                   0xF354
#define CATGL_ICON_SMASHING             0xF357

#endif /* __CATGL_ENTYPO_H */
